# version: '3.7'
# services:
#   db:
#     image: mysql:5.7
#     volumes:
#       - db_data:/var/lib/mysql
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: db
#       MYSQL_USER: user
#       MYSQL_PASSWORD: password
#   wordpress:
#     depends_on:
#       - db
#     image: wordpress:latest
#     ports:
#       - "8000:80"
#     restart: always
#     environment:
#       WORDPRESS_DB_HOST: db:3306
#       WORDPRESS_DB_USER: user
#       WORDPRESS_DB_PASSWORD: password
#       WORDPRESS_DB_NAME: db
# volumes:
#   db_data:
    

services:
  wordpress:
    image: wordpress:latest
    platform: linux/amd64
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: mariadb:latest
